### ISSUE TITLE
[Bug] plot_stamp not working

### ISSUE THREAD

**Issue by fforster** [alercebroker/alerce_client_new#13]
**Describe the bug**
When I run plot_stamp it crashes

**To Reproduce**
after loading the client, run
alerce.plot_stamp("ZTF21aaqftuq")

**Expected behavior**
we should see the first available stamps

**Screenshots**

![image](https://user-images.githubusercontent.com/5090828/112500849-81936300-8d67-11eb-88db-c8f9c1a5174b.png)

**Comment by dirodriguezm** [comment]
We changed the name to `plot_stamps`. It is working I just tested it. Here you can see the official docs with a working example: https://alerce-new-python-client.readthedocs.io/en/main/tutorials/stamps_api.html

**Comment by fforster** [comment]
I think what happened is that in the new version the funcionality to work without a candid and use the first available stamp by default was lost.
